[package]
name = "proxy-pause"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/proxy_pause.rs"

[dependencies.multiversx-sc]
version = "0.39.0"
path = "../../../framework/base"

[dependencies.multiversx-sc-modules]
version = "0.39.0"
path = "../../../contracts/modules"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.0"
path = "../../../framework/scenario"

[dev-dependencies.use-module]
path = "../../feature-tests/use-module"
