[package]
name = "composability-tests"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.forwarder]
path = "forwarder"

[dependencies.forwarder-raw]
path = "forwarder-raw"

[dependencies.promises-features]
path = "promises-features"

[dependencies.proxy-test-first]
path = "proxy-test-first"

[dependencies.proxy-test-second]
path = "proxy-test-second"

[dependencies.recursive-caller]
path = "recursive-caller"

[dependencies.vault]
path = "vault"

[dependencies.multiversx-sc]
version = "0.39.0"
path = "../../../framework/base"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.0"
path = "../../../framework/scenario"
