[package]
name = "vault-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vault]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.0"
path = "../../../../../framework/meta"
